In [44]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# Load data
data_directory = "~/Desktop/Research/dataset"
games = pd.read_csv(data_directory + "/games.csv")
boxscore = pd.read_csv(data_directory + "/boxscore.csv")
money_line = pd.read_csv(data_directory + "/money_line.csv")

games = pd.DataFrame(games)
boxscore = pd.DataFrame(boxscore)
money_line = pd.DataFrame(money_line)

# Prepare games
games["game_date"] = pd.to_datetime(games["game_date"])

# Prepare moneyline
money_line = money_line[money_line["home"] != "Off"]
money_line["date_url"] = pd.to_datetime(money_line["date_url"])
money_line["home"] = money_line["home"].astype(float)
money_line["away"] = money_line["away"].astype(float)

# Prepare boxscore
# 1. Replace all NaN elements with 0s.
boxscore = boxscore.fillna(0)

# 2. Convert datatypes to float
boxscore["fg_pct"] = boxscore["fg_pct"].astype(float)
boxscore["fg3_pct"] = boxscore["fg3_pct"].astype(float)
boxscore["ft_pct"] = boxscore["ft_pct"].astype(float)

# test
boxscore_join = boxscore[["code", "team", "player_code", "fg_pct", "fg3_pct", "ft_pct"]]
games_join = games[["code", "game_date", "home_code", "visiting_code", "home_team", "visiting_team", "winner"]]
df = pd.merge(games_join, boxscore_join, how = 'inner', on=['code', 'code'])

df["home_wins"] = np.where(df["winner"] == df["home_code"], 1, 0)
#boxscore = boxscore.groupby(["code", "team"])['player_code'].apply(' '.join).reset_index()

#df.shape
df.head(n=20)

df.pivot(index="code", column="player_code", values="fg_pct")

            code  game_date home_code visiting_code               home_team     visiting_team winner team player_code  fg_pct  fg3_pct  ft_pct  home_wins
0   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   afflaar01   0.571    0.333   1.000          1
1   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   lawsoty01   0.500    1.000   0.750          1
2   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   farieke01   0.500    0.000   1.000          1
3   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   chandwi01   0.500    0.400   1.000          1
4   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   mozgoti01   0.250    0.000   1.000          1
5   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   nurkiju01   0.333    0.000   0.667          1
6   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   harriga01   0.286    0.333   1.000          1
7   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   robinna01   0.000    0.000   0.000          1
8   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  DEN   hicksjj01   0.000    0.000   0.500          1
9   201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   butleji01   0.571    0.500   1.000          1
10  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   gasolpa01   0.412    0.000   0.750          1
11  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI    rosede01   0.280    0.333   1.000          1
12  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI    noahjo01   0.500    0.000   0.000          1
13  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   dunlemi02   0.333    0.667   0.000          1
14  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   hinriki01   1.000    1.000   0.000          1
15  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   brookaa01   0.333    0.500   1.000          1
16  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   gibsota01   0.375    0.000   0.750          1
17  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   mirotni01   0.500    0.000   0.500          1
18  201501010CHI 2015-01-01       CHI           DEN           Chicago Bulls    Denver Nuggets    CHI  CHI   snellto01   0.000    0.000   0.000          1
19  201501010MIN 2015-01-01       MIN           SAC  Minnesota Timberwolves  Sacramento Kings    SAC  SAC   collida01   0.533    0.500   1.000          0